import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "@/app/ui/styles/globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 function Header() {
  return (
    <header className="bg-slate-500 py-4">
      <div className="container mx-auto px-4">
        <nav className="flex items-center justify-between">
          <div className="flex items-center">
            <Link href="/mountain">Mountain</Link>
          </div>
          <div className="flex items-center">
            <Link href="/">Home Page</Link>
          </div>
             <div className="flex items-center">
            <Link href="/hotels">Hotel </Link>
          </div>
               <div className="flex items-center">
            <Link href="/Contacts">Contact us  </Link>
          </div>



        </nav>
      </div>
    </header>
  );
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {/* <Header/> */}
        {children}
      </body>
    </html>
  );
}
